# Generated by Django 2.2.6 on 2020-01-08 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(default=None, help_text='The user that posted this comment.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(help_text='Title of your question.', max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.CharField(blank=True, editable=False, help_text='Unique URL path to access this question. Generated by the system.', max_length=1000),
        ),
    ]
