from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=settings.QUESTION_NAME_MAX_LENGTH, unique=True,
                             help_text="Title of your question.")
    author = models.ForeignKey(User, on_delete=models.PROTECT,
                            help_text="The user that posted this question.")
    slug = models.CharField(max_length=settings.QUESTION_NAME_MAX_LENGTH, blank=True, editable=False,
                            help_text="Unique URL path to access this question. Generated by the system.")
    created = models.DateTimeField(auto_now_add=True,
                                   help_text="The date and time this question was created. Automatically generated when the model saves.")
    modified = models.DateTimeField(auto_now=True,
                                    help_text="The date and time this page was updated. Automatically generated when the model updates.")
    
    def __str__(self):
        return self.question_text

    def get_absolute_url(self):
        """ Returns a fully-qualified path for a question (/my-new-question-page). """
        path_components = {'slug': self.slug}
        return reverse('question-details-page', kwargs=path_components)

    def save(self, *args, **kwargs):
        """ Creates a URL safe slug automatically when a new a question is created. """
        if not self.pk:
            self.slug = slugify(self.question_text, allow_unicode=True)

        # Call save on the superclass.
        return super(Question, self).save(*args, **kwargs)

class Comment(models.Model):
    comment = models.CharField(max_length=200)
    question_id = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.comment